name: Deploy Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute on Ansible Control Node
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.ANSIBLE_HOST }}
          username: ${{ secrets.ANSIBLE_USER }}
          key: ${{ secrets.ANSIBLE_SSH_KEY }}

          script: |
            cd /home/cloud_user/ansible-test/ansible

            git fetch origin
            git reset --hard origin/master

            ansible-playbook -i inventory/base.inv playbooks/main.yml
